### PR TITLE
Gas stress contracts

### PR DESCRIPTION
**Pull request by vyzo**
See https://github.com/filecoin-project/ref-fvm/issues/1281

### JUMPFEST
This is a maximally sized contract that does 1M iterations of jumping around, either random or linear.
See `jmpfest-gen.ss` for how the contract is generated :hamster: 

```
vyzo@carbon6 fvm-bench $ time ./target/release/fvm-bench -b bundles/builtin-actors-next-16a587513d.car ./contracts/jmpfest_linear.bin "" ""
Result: 
Gas Used: 5389793492

real	0m1.795s
user	0m6.185s
sys	0m0.066s

vyzo@carbon6 fvm-bench $ time ./target/release/fvm-bench -b bundles/builtin-actors-next-16a587513d.car ./contracts/jmpfest_random.bin "" ""
Result: 
Gas Used: 5389848050

real	0m1.622s
user	0m5.907s
sys	0m0.078s

```

### MEMFEST
This is a maximal memory store+load contract; it initializes 10M slots (320MB) as a chain, and then does 10M traversals.
Comes in two variants, linear and random, where the traversal is dictated by a linear congruential rng.

```
vyzo@carbon6 fvm-bench $ time ./target/release/fvm-bench -b bundles/builtin-actors-next-16a587513d.car ./contracts/memfest_linear.bin "" ""
Result: 
Gas Used: 166863474809

real	0m15.282s
user	0m19.515s
sys	0m0.117s

vyzo@carbon6 fvm-bench $ time ./target/release/fvm-bench -b bundles/builtin-actors-next-16a587513d.car ./contracts/memfest_random.bin "" ""
Result: 
Gas Used: 282153298750

real	0m23.816s
user	0m28.069s
sys	0m0.075s
```

### CODE REVIEW

**Comment by Stebalien** [comment]
We should try to get the gas numbers in the second case as much as possible. Can we make them both nearly identitcal except for swapping the order of zeroing and generating a random table?

**Comment by vyzo** [comment]
I guess i can make a phony LCG that computes X' = X + 1, so yes we can make pretty much identical.

**Comment by vyzo** [comment]
apples to apples:
```
vyzo@carbon6 fvm-bench $ time ./target/release/fvm-bench -b bundles/builtin-actors-next-16a587513d.car ./contracts/memfest_linear.bin "" ""
Result: 
Gas Used: 282059900280

real	0m28.931s
user	0m33.737s
sys	0m0.095s
```

**Comment by Kubuxu** [comment]
@vyzo did you run it on your notebook (I'm assuming from the hostname), was it plugged into the charger both times?

I would recommend running it on one of the dedicated servers (the Equinix ones).

**Comment by vyzo** [comment]
yes it was plugged in.
Gas charges shouldn't change regardless, but wallclock time may fluctuate indeed.

**Comment by vyzo** [comment]
Note: I would like to dedup the code between the two contracts, and just have a small init section and then the same, but eas doesn't like it: see https://github.com/quilt/etk/issues/114

**Review by Stebalien — APPROVED** [review]

**Pull request merged**
